language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - FLASK=0.8
  - FLASK=0.9
  - FLASK=0.10
install:
  - pip install Flask==$FLASK
  - pip install speaklater
script: nosetests test_json
matrix:
  exclude:
    - python: "3.3"
      env: FLASK=0.8
    - python: "3.3"
      env: FLASK=0.9
    - python: "3.4"
      env: FLASK=0.8
    - python: "3.4"
      env: FLASK=0.9
