language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - FLASK=0.10
  - FLASK=0.10.1
  - FLASK=0.10 speaklater
  - FLASK=0.10.1 speaklater
  - FLASK=0.11
  - FLASK=0.11.1
install:
  - pip install Flask==$FLASK
  - pip install pycodestyle pytest pytest-cov
before_script:
 - pycodestyle flask_json.py
script: py.test
